//! The port is checked against the implementation it replaces, not against a
//! reading of it.
//!
//! `python_goldens.json` is generated by running the Python modules over a
//! fixed corpus. Regenerate it with `just goldens` after changing either side,
//! and read the diff: a change here is a change in what the daemon accepts.

use serde_json::Value;

fn goldens() -> Value {
    let raw = include_str!("python_goldens.json");
    serde_json::from_str(raw).expect("goldens parse")
}

fn as_usize(v: &Value) -> usize {
    v.as_u64().expect("count") as usize
}

#[test]
fn prose_assessment_matches_python() {
    for case in goldens()["prose"].as_array().unwrap() {
        let text = case["text"].as_str().unwrap();
        let got = packset_core::prose::assess(text);
        assert_eq!(got.words, as_usize(&case["words"]), "words for {text:?}");
        assert_eq!(
            got.sentences,
            as_usize(&case["sentences"]),
            "sentences for {text:?}"
        );
        assert_eq!(
            got.adverbs,
            as_usize(&case["adverbs"]),
            "adverbs for {text:?}"
        );
        assert_eq!(
            got.passives,
            as_usize(&case["passives"]),
            "passives for {text:?}"
        );
        assert_eq!(
            got.hard_sentences,
            as_usize(&case["hard_sentences"]),
            "hard for {text:?}"
        );
        assert_eq!(
            got.very_hard_sentences,
            as_usize(&case["very_hard_sentences"]),
            "very hard for {text:?}"
        );
        match case["grade"].as_f64() {
            Some(want) => {
                let got = got.grade.unwrap_or_else(|| panic!("grade for {text:?}"));
                assert!(
                    (got - want).abs() < 1e-6,
                    "grade for {text:?}: {got} {want}"
                );
            }
            None => assert_eq!(got.grade, None, "grade for {text:?}"),
        }
        match case["ease"].as_f64() {
            Some(want) => {
                let got = got.ease.unwrap_or_else(|| panic!("ease for {text:?}"));
                assert!((got - want).abs() < 1e-6, "ease for {text:?}: {got} {want}");
            }
            None => assert_eq!(got.ease, None, "ease for {text:?}"),
        }
        let want_ratio = case["adverb_ratio"].as_f64().unwrap();
        assert!(
            (got.adverb_ratio - want_ratio).abs() < 1e-6,
            "adverb ratio for {text:?}"
        );
    }
}

#[test]
fn remote_normalization_matches_python() {
    for case in goldens()["remote"].as_array().unwrap() {
        let remote = case["remote"].as_str().unwrap();
        let got = packset_core::identity::normalize_remote(remote);
        match case["workspace"].as_str() {
            Some(want) => assert_eq!(got.as_deref(), Ok(want), "{remote}"),
            None => assert!(got.is_err(), "{remote} should not normalize"),
        }
    }
}

#[test]
fn workspace_slugs_match_python() {
    for case in goldens()["slug"].as_array().unwrap() {
        let workspace = case["workspace"].as_str().unwrap();
        let want = case["slug"].as_str().unwrap();
        assert_eq!(
            packset_core::identity::workspace_slug(workspace),
            want,
            "{workspace:?}"
        );
    }
}

#[test]
fn set_names_match_python() {
    for case in goldens()["set"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let got = packset_core::set_name::check(name);
        match case["set"].as_str() {
            Some(want) => assert_eq!(got.as_deref(), Ok(want), "{name:?}"),
            None => assert!(got.is_err(), "{name:?} should be refused"),
        }
    }
}
